Update GitHub Actions workflow and Couchbase configuration

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -1,29 +1,96 @@
 name: Tests
+
 on:
   push:
-    workflow_dispatch:
-    schedule:
-    - cron: "0 0 * * 0"
+    branches: [main]
+  pull_request:
+    branches: [main]
+  schedule:
+    - cron: "0 */6 * * *"
+
 jobs:
   run_tests:
     name: Run Tests
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        java-version: ["8", "11", "17"]
     steps:
-      - uses: actions/checkout@v2
-      - name: Set up JDK 17
-        uses: actions/setup-java@v2
-        with:
-          java-version: 17
-          distribution: 'adopt'
-          cache: gradle
-      - id: run
+      - name: Update repositories
         run: |
-          ./gradlew --no-daemon test
+          apt update || echo "apt-update failed" # && apt -y upgrade
+
+      - name: Set up JDK ${{ matrix.java-version }}
+        uses: actions/setup-java@v4
+        with:
+          java-version: ${{ matrix.java-version }}
+          distribution: "adopt"
+          cache: gradle
+
+      - name: Checkout ${{ github.event.repository.name }}
+        uses: actions/checkout@v4
+
+      - name: Setup couchbase
+        run: |
+          apt install -y iputils-ping || echo "apt-install failed"
+          ping -c 1 couchbase && (
+            apt install -y socat
+            socat TCP-LISTEN:8091,fork TCP:couchbase:8091 &
+            socat TCP-LISTEN:8092,fork TCP:couchbase:8092 &
+            socat TCP-LISTEN:8093,fork TCP:couchbase:8093 &
+            socat TCP-LISTEN:8094,fork TCP:couchbase:8094 &
+            socat TCP-LISTEN:8095,fork TCP:couchbase:8095 &
+            socat TCP-LISTEN:8096,fork TCP:couchbase:8096 &
+            socat TCP-LISTEN:9140,fork TCP:couchbase:9140 &
+            socat TCP-LISTEN:11210,fork TCP:couchbase:11210 &
+            socat TCP-LISTEN:11211,fork TCP:couchbase:11211 &
+            socat TCP-LISTEN:11207,fork TCP:couchbase:11207 &
+            socat TCP-LISTEN:18091,fork TCP:couchbase:18091 &
+            socat TCP-LISTEN:18092,fork TCP:couchbase:18092 &
+            socat TCP-LISTEN:18093,fork TCP:couchbase:18093 &
+            socat TCP-LISTEN:18094,fork TCP:couchbase:18094 &
+            socat TCP-LISTEN:18095,fork TCP:couchbase:18095 &
+            socat TCP-LISTEN:18096,fork TCP:couchbase:18096 &
+          ) && echo "Initialized couchbase port forwarding" || echo "ping couchbase failed, not forwarding ports"
+          printf "Waiting for CB startup..."
+          wget -O /dev/null  http://localhost:8091/ && echo "DONE" || (echo "FAIL" && panic)
+          curl  -v -X POST http://localhost:8091/node/controller/setupServices -d 'services=kv%2Cn1ql%2Cindex'
+          curl  -v -X POST http://localhost:8091/pools/default -d 'memoryQuota=256' -d 'indexMemoryQuota=256'
+          curl  -u Administrator:password -v -X POST http://localhost:8091/settings/web -d 'password=password&username=Administrator&port=SAME'
+          curl -v -X POST http://localhost:8091/pools/default/buckets \
+            -u Administrator:password \
+            -d name=user_profile \
+            -d bucketType=couchbase\
+            -d ramQuotaMB=1024 \
+            -d durabilityMinLevel=majorityAndPersistActive
+          curl  -u Administrator:password -v -X POST http://localhost:8091/settings/indexes -d 'storageMode=memory_optimized'
+          curl  -u Administrator:password -v -X GET http://localhost:8091/pools/default | jq '.' | grep hostname
+          curl  -u Administrator:password -v -X POST http://localhost:8091/sampleBuckets/install -d '["travel-sample"]'
+
+      - name: Run Gradle Tests
+        id: run
+        run: ./gradlew --no-daemon test
+
       - name: Report Status
         if: always()
         uses: ravsamhq/notify-slack-action@v1
         with:
           status: ${{ job.status }}
-          notify_when: 'failure'
+          notify_when: "failure"
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+
+    services:
+      couchbase:
+        image: public.ecr.aws/z2f7n8a1/couchbase-da-containers:couchbase-neo
+        options: >-
+          --health-cmd "wget -q -O - localhost:8091"
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 10
+        ports:
+          - 8091-8096
+          - 9140
+          - 11210-11211
+          - 11207
+          - 18091-18096
